apiVersion: v1
kind: Service
metadata:
  name: {{ include "reposwarm.fullname" . }}-api
  labels:
    {{- include "reposwarm.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: {{ .Release.Name }}
