#!/bin/bash
set -euo pipefail

# ============================================================
# RepoSwarm — Cloud-init / User Data Script
# ============================================================

export DEBIAN_FRONTEND=noninteractive

echo ">>> Installing dependencies..."
apt-get update -y
apt-get install -y ca-certificates curl gnupg jq unzip

echo ">>> Installing AWS CLI v2..."
ARCH=$(uname -m)
if [ "$ARCH" = "aarch64" ]; then
  CLI_ARCH="aarch64"
else
  CLI_ARCH="x86_64"
fi
curl -fsSL "https://awscli.amazonaws.com/awscli-exe-linux-$CLI_ARCH.zip" -o /tmp/awscliv2.zip
unzip -q /tmp/awscliv2.zip -d /tmp
/tmp/aws/install
rm -rf /tmp/awscliv2.zip /tmp/aws

echo ">>> Installing Docker..."
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc

echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  tee /etc/apt/sources.list.d/docker.list > /dev/null

apt-get update -y
apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
usermod -aG docker ubuntu

echo ">>> Creating RepoSwarm directory..."
mkdir -p /opt/reposwarm
cd /opt/reposwarm

# --- Fetch secrets from Secrets Manager ---
echo ">>> Fetching secrets..."

API_TOKEN=""
if [ -n "${api_token_secret}" ]; then
  API_TOKEN=$(aws secretsmanager get-secret-value \
    --secret-id "${api_token_secret}" \
    --region "${aws_region}" \
    --query SecretString --output text 2>/dev/null || echo "")
fi

GITHUB_TOKEN=""
if [ -n "${github_token_secret}" ]; then
  GITHUB_TOKEN=$(aws secretsmanager get-secret-value \
    --secret-id "${github_token_secret}" \
    --region "${aws_region}" \
    --query SecretString --output text 2>/dev/null || echo "")
fi

ANTHROPIC_KEY=""
if [ -n "${anthropic_secret}" ]; then
  ANTHROPIC_KEY=$(aws secretsmanager get-secret-value \
    --secret-id "${anthropic_secret}" \
    --region "${aws_region}" \
    --query SecretString --output text 2>/dev/null || echo "")
fi

# --- Write .env file ---
echo ">>> Writing .env file..."
cat > /opt/reposwarm/.env <<ENVEOF
# Auto-generated by Terraform user-data
AWS_REGION=${aws_region}
DYNAMODB_TABLE=${dynamodb_table}
API_BEARER_TOKEN=$API_TOKEN
GITHUB_TOKEN=$GITHUB_TOKEN
ANTHROPIC_API_KEY=$ANTHROPIC_KEY
CLAUDE_CODE_USE_BEDROCK=${use_bedrock ? "1" : "0"}
TEMPORAL_SERVER_URL=temporal:7233
TEMPORAL_NAMESPACE=default
TEMPORAL_TASK_QUEUE=investigate-task-queue
ENVEOF

chmod 600 /opt/reposwarm/.env

# --- Write docker-compose.yml (base64-encoded to avoid interpolation issues) ---
echo ">>> Writing docker-compose.yml..."
echo "${compose_file}" | base64 -d > /opt/reposwarm/docker-compose.yml

# --- Write nginx.conf ---
echo ">>> Writing nginx.conf..."
echo "${nginx_conf}" | base64 -d > /opt/reposwarm/nginx.conf

# --- Start services ---
echo ">>> Starting RepoSwarm..."
cd /opt/reposwarm
docker compose up -d

echo ">>> RepoSwarm deployment complete!"
